# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'M3UExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'mobile-ffmpeg-full', '3.1'
  pod 'Alamofire'

  # Pods for M3UExample

end
