# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'M3UExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #保持4.4以上
  pod 'mobile-ffmpeg-full'
  pod 'Alamofire'

  # Pods for M3UExample

end
